eureka:
  client:
    service-url:
      defaultZone: http://localhost:8998/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: restaurantprjt
    password: restaurantprjt
